# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := rtc_base
DEFS_Debug := \
	'-DV8_DEPRECATION_WARNINGS' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DCHROMIUM_BUILD' \
	'-DCR_CLANG_REVISION=231191-2' \
	'-DTOOLKIT_VIEWS=1' \
	'-DUI_COMPOSITOR_IMAGE_TRANSPORT' \
	'-DUSE_AURA=1' \
	'-DUSE_ASH=1' \
	'-DUSE_PANGO=1' \
	'-DUSE_CAIRO=1' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_X11=1' \
	'-DUSE_CLIPBOARD_AURAX11=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DENABLE_PRE_SYNC_BACKUP' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_PEPPER_CDMS' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_NOTIFICATIONS' \
	'-DUSE_UDEV' \
	'-DDONT_EMBED_BUILD_METADATA' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_AUTOFILL_DIALOG=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DCLD_VERSION=2' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_BASIC_PRINTING=1' \
	'-DENABLE_PRINT_PREVIEW=1' \
	'-DENABLE_SPELLCHECK=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_APP_LIST=1' \
	'-DENABLE_SETTINGS_APP=1' \
	'-DENABLE_SUPERVISED_USERS=1' \
	'-DENABLE_MDNS=1' \
	'-DENABLE_SERVICE_DISCOVERY=1' \
	'-DV8_USE_EXTERNAL_STARTUP_DATA' \
	'-DEXPAT_RELATIVE_PATH' \
	'-DWEBRTC_POSIX' \
	'-DWEBRTC_LINUX' \
	'-DFEATURE_ENABLE_SSL' \
	'-DLOGGING=1' \
	'-DSSL_USE_NSS' \
	'-DHAVE_NSS_SSL_H' \
	'-DSSL_USE_NSS_RNG' \
	'-DWEBRTC_H264_BUILD' \
	'-DUSE_LIBPCI=1' \
	'-DUSE_GLIB=1' \
	'-DUSE_NSS=1' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG' \
	'-D_GLIBCXX_DEBUG=1'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-strict-aliasing \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wno-reserved-user-defined-literal \
	-B/home/lizhiyong/linux/trunk64/webrtc/src/third_party/binutils/Linux_x64/Release/bin \
	-Wheader-hygiene \
	-Wno-char-subscripts \
	-Wno-unneeded-internal-declaration \
	-Wno-covered-switch-default \
	-Wstring-conversion \
	-Wno-c++11-narrowing \
	-Wno-deprecated-register \
	-Wno-inconsistent-missing-override \
	-Wno-unused-private-field \
	-Wno-reorder \
	-Wno-unused-variable \
	-Wno-writable-strings \
	-Wno-unsequenced \
	-Wno-unused-const-variable \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-Wno-strict-overflow \
	-Wimplicit-fallthrough \
	-Wthread-safety \
	-I/usr/include/nss \
	-I/usr/include/nspr \
	-Wno-header-guard \
	-m64 \
	-march=x86-64 \
	-O0 \
	-g \
	-gdwarf-4 \
	-funwind-tables \
	-gsplit-dwarf \
	-Wno-undefined-bool-conversion \
	-Wno-tautological-undefined-compare

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-exceptions \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare \
	-std=gnu++11 \
	-Woverloaded-virtual

INCS_Debug := \
	-I$(obj)/gen \
	-I. \
	-Ithird_party/jsoncpp/overrides/include \
	-Ithird_party/jsoncpp/source/include \
	-Ichromium/src/third_party/jsoncpp/overrides/include \
	-Ichromium/src/third_party/jsoncpp/source/include \
	-Inet/third_party/nss/ssl

DEFS_Release := \
	'-DV8_DEPRECATION_WARNINGS' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DCHROMIUM_BUILD' \
	'-DCR_CLANG_REVISION=231191-2' \
	'-DTOOLKIT_VIEWS=1' \
	'-DUI_COMPOSITOR_IMAGE_TRANSPORT' \
	'-DUSE_AURA=1' \
	'-DUSE_ASH=1' \
	'-DUSE_PANGO=1' \
	'-DUSE_CAIRO=1' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_X11=1' \
	'-DUSE_CLIPBOARD_AURAX11=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DENABLE_PRE_SYNC_BACKUP' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_PEPPER_CDMS' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_NOTIFICATIONS' \
	'-DUSE_UDEV' \
	'-DDONT_EMBED_BUILD_METADATA' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_AUTOFILL_DIALOG=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DCLD_VERSION=2' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_BASIC_PRINTING=1' \
	'-DENABLE_PRINT_PREVIEW=1' \
	'-DENABLE_SPELLCHECK=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_APP_LIST=1' \
	'-DENABLE_SETTINGS_APP=1' \
	'-DENABLE_SUPERVISED_USERS=1' \
	'-DENABLE_MDNS=1' \
	'-DENABLE_SERVICE_DISCOVERY=1' \
	'-DV8_USE_EXTERNAL_STARTUP_DATA' \
	'-DEXPAT_RELATIVE_PATH' \
	'-DWEBRTC_POSIX' \
	'-DWEBRTC_LINUX' \
	'-DFEATURE_ENABLE_SSL' \
	'-DLOGGING=1' \
	'-DSSL_USE_NSS' \
	'-DHAVE_NSS_SSL_H' \
	'-DSSL_USE_NSS_RNG' \
	'-DWEBRTC_H264_BUILD' \
	'-DUSE_LIBPCI=1' \
	'-DUSE_GLIB=1' \
	'-DUSE_NSS=1' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0'

# Flags passed to all source files.
CFLAGS_Release := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-strict-aliasing \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wno-reserved-user-defined-literal \
	-B/home/lizhiyong/linux/trunk64/webrtc/src/third_party/binutils/Linux_x64/Release/bin \
	-Wheader-hygiene \
	-Wno-char-subscripts \
	-Wno-unneeded-internal-declaration \
	-Wno-covered-switch-default \
	-Wstring-conversion \
	-Wno-c++11-narrowing \
	-Wno-deprecated-register \
	-Wno-inconsistent-missing-override \
	-Wno-unused-private-field \
	-Wno-reorder \
	-Wno-unused-variable \
	-Wno-writable-strings \
	-Wno-unsequenced \
	-Wno-unused-const-variable \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-Wno-strict-overflow \
	-Wimplicit-fallthrough \
	-Wthread-safety \
	-I/usr/include/nss \
	-I/usr/include/nspr \
	-Wno-header-guard \
	-m64 \
	-march=x86-64 \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections \
	-funwind-tables

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-exceptions \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare \
	-std=gnu++11 \
	-Woverloaded-virtual

INCS_Release := \
	-I$(obj)/gen \
	-I. \
	-Ithird_party/jsoncpp/overrides/include \
	-Ithird_party/jsoncpp/source/include \
	-Ichromium/src/third_party/jsoncpp/overrides/include \
	-Ichromium/src/third_party/jsoncpp/source/include \
	-Inet/third_party/nss/ssl

OBJS := \
	$(obj).target/$(TARGET)/webrtc/base/asyncfile.o \
	$(obj).target/$(TARGET)/webrtc/base/asynchttprequest.o \
	$(obj).target/$(TARGET)/webrtc/base/asyncinvoker.o \
	$(obj).target/$(TARGET)/webrtc/base/asyncpacketsocket.o \
	$(obj).target/$(TARGET)/webrtc/base/asyncresolverinterface.o \
	$(obj).target/$(TARGET)/webrtc/base/asyncsocket.o \
	$(obj).target/$(TARGET)/webrtc/base/asynctcpsocket.o \
	$(obj).target/$(TARGET)/webrtc/base/asyncudpsocket.o \
	$(obj).target/$(TARGET)/webrtc/base/autodetectproxy.o \
	$(obj).target/$(TARGET)/webrtc/base/bandwidthsmoother.o \
	$(obj).target/$(TARGET)/webrtc/base/base64.o \
	$(obj).target/$(TARGET)/webrtc/base/buffer.o \
	$(obj).target/$(TARGET)/webrtc/base/bytebuffer.o \
	$(obj).target/$(TARGET)/webrtc/base/common.o \
	$(obj).target/$(TARGET)/webrtc/base/cpumonitor.o \
	$(obj).target/$(TARGET)/webrtc/base/crc32.o \
	$(obj).target/$(TARGET)/webrtc/base/cryptstring.o \
	$(obj).target/$(TARGET)/webrtc/base/dbus.o \
	$(obj).target/$(TARGET)/webrtc/base/diskcache.o \
	$(obj).target/$(TARGET)/webrtc/base/filelock.o \
	$(obj).target/$(TARGET)/webrtc/base/fileutils.o \
	$(obj).target/$(TARGET)/webrtc/base/firewallsocketserver.o \
	$(obj).target/$(TARGET)/webrtc/base/flags.o \
	$(obj).target/$(TARGET)/webrtc/base/helpers.o \
	$(obj).target/$(TARGET)/webrtc/base/httpbase.o \
	$(obj).target/$(TARGET)/webrtc/base/httpclient.o \
	$(obj).target/$(TARGET)/webrtc/base/httpcommon.o \
	$(obj).target/$(TARGET)/webrtc/base/httprequest.o \
	$(obj).target/$(TARGET)/webrtc/base/httpserver.o \
	$(obj).target/$(TARGET)/webrtc/base/ipaddress.o \
	$(obj).target/$(TARGET)/webrtc/base/json.o \
	$(obj).target/$(TARGET)/webrtc/base/latebindingsymboltable.o \
	$(obj).target/$(TARGET)/webrtc/base/libdbusglibsymboltable.o \
	$(obj).target/$(TARGET)/webrtc/base/linux.o \
	$(obj).target/$(TARGET)/webrtc/base/linuxfdwalk.o \
	$(obj).target/$(TARGET)/webrtc/base/logging.o \
	$(obj).target/$(TARGET)/webrtc/base/messagedigest.o \
	$(obj).target/$(TARGET)/webrtc/base/messagehandler.o \
	$(obj).target/$(TARGET)/webrtc/base/messagequeue.o \
	$(obj).target/$(TARGET)/webrtc/base/multipart.o \
	$(obj).target/$(TARGET)/webrtc/base/natserver.o \
	$(obj).target/$(TARGET)/webrtc/base/natsocketfactory.o \
	$(obj).target/$(TARGET)/webrtc/base/nattypes.o \
	$(obj).target/$(TARGET)/webrtc/base/nethelpers.o \
	$(obj).target/$(TARGET)/webrtc/base/network.o \
	$(obj).target/$(TARGET)/webrtc/base/optionsfile.o \
	$(obj).target/$(TARGET)/webrtc/base/pathutils.o \
	$(obj).target/$(TARGET)/webrtc/base/physicalsocketserver.o \
	$(obj).target/$(TARGET)/webrtc/base/posix.o \
	$(obj).target/$(TARGET)/webrtc/base/profiler.o \
	$(obj).target/$(TARGET)/webrtc/base/proxydetect.o \
	$(obj).target/$(TARGET)/webrtc/base/proxyinfo.o \
	$(obj).target/$(TARGET)/webrtc/base/proxyserver.o \
	$(obj).target/$(TARGET)/webrtc/base/ratelimiter.o \
	$(obj).target/$(TARGET)/webrtc/base/ratetracker.o \
	$(obj).target/$(TARGET)/webrtc/base/sha1.o \
	$(obj).target/$(TARGET)/webrtc/base/sha1digest.o \
	$(obj).target/$(TARGET)/webrtc/base/sharedexclusivelock.o \
	$(obj).target/$(TARGET)/webrtc/base/signalthread.o \
	$(obj).target/$(TARGET)/webrtc/base/sigslot.o \
	$(obj).target/$(TARGET)/webrtc/base/socketadapters.o \
	$(obj).target/$(TARGET)/webrtc/base/socketaddress.o \
	$(obj).target/$(TARGET)/webrtc/base/socketaddresspair.o \
	$(obj).target/$(TARGET)/webrtc/base/socketpool.o \
	$(obj).target/$(TARGET)/webrtc/base/socketstream.o \
	$(obj).target/$(TARGET)/webrtc/base/ssladapter.o \
	$(obj).target/$(TARGET)/webrtc/base/sslfingerprint.o \
	$(obj).target/$(TARGET)/webrtc/base/sslidentity.o \
	$(obj).target/$(TARGET)/webrtc/base/sslsocketfactory.o \
	$(obj).target/$(TARGET)/webrtc/base/sslstreamadapter.o \
	$(obj).target/$(TARGET)/webrtc/base/sslstreamadapterhelper.o \
	$(obj).target/$(TARGET)/webrtc/base/stream.o \
	$(obj).target/$(TARGET)/webrtc/base/systeminfo.o \
	$(obj).target/$(TARGET)/webrtc/base/task.o \
	$(obj).target/$(TARGET)/webrtc/base/taskparent.o \
	$(obj).target/$(TARGET)/webrtc/base/taskrunner.o \
	$(obj).target/$(TARGET)/webrtc/base/testclient.o \
	$(obj).target/$(TARGET)/webrtc/base/thread.o \
	$(obj).target/$(TARGET)/webrtc/base/timing.o \
	$(obj).target/$(TARGET)/webrtc/base/transformadapter.o \
	$(obj).target/$(TARGET)/webrtc/base/unixfilesystem.o \
	$(obj).target/$(TARGET)/webrtc/base/urlencode.o \
	$(obj).target/$(TARGET)/webrtc/base/versionparsing.o \
	$(obj).target/$(TARGET)/webrtc/base/virtualsocketserver.o \
	$(obj).target/$(TARGET)/webrtc/base/worker.o \
	$(obj).target/$(TARGET)/webrtc/base/x11windowpicker.o \
	$(obj).target/$(TARGET)/webrtc/base/nssidentity.o \
	$(obj).target/$(TARGET)/webrtc/base/nssstreamadapter.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/chromium/src/build/linux/ssl.stamp

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-Wl,--fatal-warnings \
	-Wl,-z,defs \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-fuse-ld=gold \
	-B/home/lizhiyong/linux/trunk64/webrtc/src/third_party/binutils/Linux_x64/Release/bin \
	-Wl,--disable-new-dtags \
	-m64 \
	-Wl,--detect-odr-violations \
	-Wl,--icf=safe

LDFLAGS_Release := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-Wl,--fatal-warnings \
	-Wl,-z,defs \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-fuse-ld=gold \
	-B/home/lizhiyong/linux/trunk64/webrtc/src/third_party/binutils/Linux_x64/Release/bin \
	-Wl,--disable-new-dtags \
	-m64 \
	-Wl,--detect-odr-violations \
	-Wl,--icf=safe \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := \
	

$(obj).target/webrtc/base/librtc_base.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/webrtc/base/librtc_base.a: LIBS := $(LIBS)
$(obj).target/webrtc/base/librtc_base.a: TOOLSET := $(TOOLSET)
$(obj).target/webrtc/base/librtc_base.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink_thin)

all_deps += $(obj).target/webrtc/base/librtc_base.a
# Add target alias
.PHONY: rtc_base
rtc_base: $(obj).target/webrtc/base/librtc_base.a

# Add target alias to "all" target.
.PHONY: all
all: rtc_base

