# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := rtc_base_tests
### Rules for final target.
$(obj).target/webrtc/base/rtc_base_tests.stamp: TOOLSET := $(TOOLSET)
$(obj).target/webrtc/base/rtc_base_tests.stamp:  FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/webrtc/base/rtc_base_tests.stamp
# Add target alias
.PHONY: rtc_base_tests
rtc_base_tests: $(obj).target/webrtc/base/rtc_base_tests.stamp

# Add target alias to "all" target.
.PHONY: all
all: rtc_base_tests

